---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-nginx-proxy-conf
  labels:
    app: opentelemetry
    component: otel-nginx-proxy-conf
data:
  nginx.conf: |
    worker_processes  1;
    error_log /var/log/nginx/error.log;
    events {
        worker_connections  1024;
    }

    http {
        access_log /var/log/nginx/access.log;

        ssl_certificate /var/secrets/cert.pem;
        ssl_certificate_key /var/secrets/cert-key.pem;

        upstream otel {
            server otel-control-plane-collector.default.svc.cluster.local:4317;
        }
 
        server {
            listen       8081 ssl http2;
            server_name  localhost;

            
            location / {
                grpc_pass grpc://otel;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: otel-nginx-proxy
  labels:
    app: opentelemetry
    component: otel-nginx-proxy
spec:
  ports:
  - name: grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    component: otel-nginx-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-nginx-proxy
  labels:
    app: opentelemetry
    component: otel-nginx-proxy
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-nginx-proxy
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-nginx-proxy
    spec:
      containers:
      - image: nginx:1.22
        name: nginx
        ports:
          - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: data
            subPath: nginx.conf
            readOnly: true
          - name: secrets
            mountPath: "/var/secrets/"
            readOnly: true
      volumes:
        - name: data
          configMap:
            name: otel-nginx-proxy-conf
        - name: secrets
          secret:
            secretName: otel-collector-secrets